name: live_icon
description: A flutter plugin to change the app icons and label in real time.
version: 0.0.1
repository: https://github.com/DevsOnFlutter/flutter_live_icon
documentation: https://github.com/DevsOnFlutter/flutter_live_icon/blob/main/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hackthedeveloper.live_icon
        pluginClass: LiveIconPlugin
      ios:
        pluginClass: LiveIconPlugin
